### ISSUE TITLE
Guide_Mobile_iphone5(320px): footer icons display within sidenav drawer when opened causing interaction and display issues

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#1]
![screen shot 2016-12-22 at 11 25 46 pm](https://cloud.githubusercontent.com/assets/10051544/21447110/a1fefbce-c89d-11e6-937c-09c3833effce.png)

**Comment by MarianoMiguel** [comment]
Solved
