### ISSUE TITLE
Bypassing Pre-Screen directs to QA version of Toolkit Builder, not production

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/city-accelerator-website#103]
This bug occurs only when accessing the toolkit activities via this link: 
![screen shot 2017-01-27 at 11 42 43 am copy](https://cloud.githubusercontent.com/assets/12397944/22379355/01c158f4-e487-11e6-9b22-01ff2ecf9be7.png)

Following that link leads to the toolkit builder being mostly completely cut-off:
![screen shot 2017-01-27 at 11 42 52 am](https://cloud.githubusercontent.com/assets/12397944/22379160/2b1c5baa-e486-11e6-9315-0ee05206e5b4.png)

**Comment by esalling23** [comment]
Content issue. Fixed.
