### ISSUE TITLE
Guide: Because Executive summary should be the first page upon load, the introduction is still being loaded as the first page. Needs to come second

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#115]
1. click on guide
2. start reading 
3. executive summary loads (this is correct) but introduction should be the next page, NOT back one page. 

It is confusing i think because introduction is typically the first page in a thing. but in this case. think of executive summary as the FIRST page. THEN introduction

**Comment by esalling23** [comment]
I believe this is a content issue! The Introduction page should be dragged beneath the Executive Summary page in the list in Keystone!

**Comment by esalling23** [comment]
Fixed!

**Comment by jpailthorpe** [comment]
yep. fixed!
