### ISSUE TITLE
Homepage: New design needs to be implemented before end of week. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#20]
this is a big deal since I don't want to show stakeholders until this is integrated.

new homepage from stakeholders so would love to have that in there (the new blue map background design with the pencil/eraser/etc. tool images, as well as photos replacing map images in cards)

**Comment by jpailthorpe** [comment]
https://marvelapp.com/2gjiih4/screen/17893897

**Comment by MarianoMiguel** [comment]
Going to give priority to this one

**Comment by johnnycrich** [comment]
@jpailthorpe where can the assets for the sticky notes be found, and what do they do?

**Comment by jpailthorpe** [comment]
considering final version finished and closing. Stakeholders did not find value or care in stickynote design, and though i think its neat, bigger fish to fry
