### ISSUE TITLE
Guide_home: the sidenav bar shouldn't dispaly on the guide home page and only when you start reading

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#28]
Also the contents of the guide pages are not loading within the sidebar on this page. They do load once you get into the article. I would rather have someone come to this guide home page and be drawn to the two primary actions (start reading) + (download) rather than confuse them with another action item.

**Comment by MarianoMiguel** [comment]
Ah yes, they are not displaying cause this page was probably not given access to the list of articles (basically a back-end - front-end connection issue). Anyway, I think it makes sense. I'm removing it for now.
