### ISSUE TITLE
Headerbackground: need to replace header background with better icon design

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#29]
Now that we have that con background, it is a bit hard to read the nav link text since it is noisey. Not sure about what to do here other than add a background to nav items, maybe changing the color of the text itself?

**Comment by MarianoMiguel** [comment]
@jpailthorpe I think it would be useful to involve Michael in the discussion since it's more design related

**Comment by jpailthorpe** [comment]
@MarianoMiguel Agreed. i moved this to the next milestone to give a bit more time

**Comment by msuen** [comment]
@jpailthorpe Let's tone the icons' opacity down, and bold the main nav links.

@MarianoMiguel, if you need the image again:

![ctcrepeat_clear640_360](https://cloud.githubusercontent.com/assets/2809369/22164569/caa7f780-df25-11e6-847e-b07ffa82d7cb.png)

**Comment by jpailthorpe** [comment]
This is an old DUP of #52 , so I am going to incorpoate the bolding of nav links (good idea) in the other issue, and closing this for now
