### ISSUE TITLE
Home_Css: Margins on home page when in mobile 320px range are much too wide causing content to display funky

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#3]
This is a similar issue with the mobile version of the guide. I think narrowing the margins and perhaps lowering font would fix problem. The guide, for example, looks great. 

![screen shot 2016-12-22 at 11 31 22 pm](https://cloud.githubusercontent.com/assets/10051544/21447140/26b7bce8-c89e-11e6-8083-d8a217171947.png)

**Comment by jpailthorpe** [comment]
another good example is how the game page cards are displayed.

**Comment by MarianoMiguel** [comment]
Got it. I just put together a couple responsive classes for our .wrapper, so now instead of just having size variants like .wrapper--large, we have size variants across breakpoints, so we can do .wrapper (normal wrapper on mobile) .wrapper--large@medium (large wrapper on tablets + up)

**Comment by MarianoMiguel** [comment]
This one is fixed. We can re-open if the issue appears somewhere else, but the class structure to solve it has already been created :)
