### ISSUE TITLE
Sidenav_Tab(guide+activities): on mobile, the sidenav tab is quite annoying since it extends across the screen and floats in place, obstructing view. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#4]
I wonder if we can make it appear only when scrolling back up ?

![screen shot 2016-12-22 at 11 34 56 pm](https://cloud.githubusercontent.com/assets/10051544/21447171/d2d96d1e-c89e-11e6-9446-a2b2ab40efd9.png)

**Comment by jpailthorpe** [comment]
or maybe it is just hovering a bit too low, which is why it is bothering me.

**Comment by jpailthorpe** [comment]
the back button is also floating in a weird spot which overlaps content

**Comment by MarianoMiguel** [comment]
I'm making it so that the button is fixed to the bottom of the viewport on mobile devices

![kapture 2017-01-02 at 15 12 26](https://cloud.githubusercontent.com/assets/880223/21594399/dbdec8fe-d100-11e6-96df-488f8ee18bbb.gif)

**Comment by jpailthorpe** [comment]
great!

**Comment by MarianoMiguel** [comment]
Closing it for now. We can re-visit if Michael comes up with a better solution or any tweaks
