### ISSUE TITLE
CaseStudiesHome: Images for case studies are in-properly scaling and warping, as well as appearing blown out

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#40]
*Assigning both @johnnycrich and @MarianoMiguel because i am not sure if this is cloudinary/keystone thing or a front css thing.*

Each image is of high res. and quality, so I am not sure why this is happening. I did some poking in the code and in cloudinary but can't seem to figure it out. 

Basically just want the images to crop and scale properly in all screen sizes. This is also happening on the game page as well (will ref. in other issue)

**Comment by MarianoMiguel** [comment]
@jpailthorpe I see the issue in #41 but I'm not being able to identify this one. Could you take a screenshot of what's wrong?

**Comment by jpailthorpe** [comment]
I think its better to see how the original image looks compared to how it is looking in the containers on the site. It is stretching with the containers. Maybe we just need to have the images sized appropriately with the containers and have multiple images for each container transform? Idk if thats overkill or if there is a better way to do this. 

![screen shot 2017-01-06 at 4 52 30 pm](https://cloud.githubusercontent.com/assets/10051544/21734138/d96952c4-d42f-11e6-870c-527c21359188.png)
![screen shot 2017-01-06 at 4 52 14 pm](https://cloud.githubusercontent.com/assets/10051544/21734139/d96add74-d42f-11e6-90f2-17013051b88d.png)

**Comment by MarianoMiguel** [comment]
@jpailthorpe Ah, I see now. Thanks! :)

**Comment by jpailthorpe** [comment]
2560 ✖ 3484
![case studies](https://cloud.githubusercontent.com/assets/10051544/21827456/aa251980-d759-11e6-8fec-14b790f59a1e.png)

**Comment by jpailthorpe** [comment]
you can see that the images are still stretching

**Comment by jpailthorpe** [comment]
Last image didn't include the latest commmit, but there is now a problem with text overlap +sizing. 

![screenshot-qa cityaccelerator net-2017-01-10-17-43-48](https://cloud.githubusercontent.com/assets/10051544/21827910/b1df658e-d75b-11e6-9b53-443f79adb687.png)
this is how it looks on browser windows 2000+ now.

**Comment by MarianoMiguel** [comment]
@jpailthorpe I'll be pushing an update soon that should solve this
