### ISSUE TITLE
CaseStudies Home: Text on image cards are difficult to read

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#42]
The white text on the images are hard to read. I think in Michael's mockup he has a gradient on the image to address this. I can upload images with gradients on them, but I think this might be better done in code. 

If it isn't a gradient, we will need a solution here.

**Comment by esalling23** [comment]
@jpailthorpe Do we have a designed solution for this?

**Comment by esalling23** [comment]
@jpailthorpe Looks like a design solution was implemented, now this needs review to confirm that solution works!

**Comment by jpailthorpe** [comment]
could be better, but usable. closing
