### ISSUE TITLE
About page: Header images section + Image gallery needs style

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#44]
We included a header image to show off the cohort (this was not in michael's mock, but it is important to stakeholders). Just needs to have style. 

The image gallery seems to have some hardcoded width+height dimensions, which need to be removed so that the image is responsive

**Comment by MarianoMiguel** [comment]
@jpailthorpe The styles for the header images are done, just a matter of adding the proper .s-gallery class to the container. Regarding the gallery images (which I assume you mean those 4 images next to each other), it's not a matter of hardcoded widths, but that there's only 1 image https://res.cloudinary.com/engagement-lab-home/image/upload/v1482431333/k3liuts0efpdvr3zq1cb.png

**Comment by jpailthorpe** [comment]
yeah this was a cloudinary thing. all good now!
