### ISSUE TITLE
Toolkit_MVP PDF print: When saving/printing as a pdf, each activity is starting at a new page, but will cut off content that doesn't fit into one page. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#5]
I like the fact that a new activity always starts at the top of a new page, but we can't have content be cutting off.

![screen shot 2016-12-22 at 11 46 21 pm](https://cloud.githubusercontent.com/assets/10051544/21447264/41b221e4-c8a0-11e6-9b90-f48f26cdec3a.png)

**Comment by jpailthorpe** [comment]
It looks much better and all content is at least visible so we are def. out of critical water. But I will keep this open until you feel comfortable with it.

**Comment by jpailthorpe** [comment]
trying to get a sense of where we are at holistically. based on some tests it seems like you addressed this issue (where content was cutting off when trying to print) and now each activity just page breaks at the end, which is what we wanted. 

In your commit you noted you are still working on this. Is there another issue I am not finding? @MarianoMiguel

**Comment by MarianoMiguel** [comment]
@jpailthorpe I've found that sometimes text gets cut off between pages & small inconsistencies like that. I think the most urgent matter was solved, but I'm still trying to polish it out a bit more
