### ISSUE TITLE
Case Study pages: Need to add images in each case study narrative 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#51]
this is a content thing in keystone.

**Comment by jpailthorpe** [comment]
You will need to upload these to cloudinary and then use the given url to embed the IMG in the markdown field manually. The images you want are in the guide. Use the indesign file and select a few images that look good and paste them between /at top of paragraphs. Just 1 or 2 maximum, but use your own judgement.

**Comment by jpailthorpe** [comment]
hold on this until I do a new design draft.

**Comment by msuen** [comment]
@jpailthorpe Need my input?

**Comment by jpailthorpe** [comment]
@msuen we good! Just going to keep it clean I think and only include team photos.
