### ISSUE TITLE
Global: Change header images to mockups, nix icon design 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#52]
I'm not sure if this is something that is also reliant on cloudinary settings. 

Johnny/Erica, wanna take a look before Mariano just to make sure?

**Comment by esalling23** [comment]
This is due to a setting of 1000px width that is set on the front-end when the image is loaded on the page. I have changed it to 800px, but in general this could be changed by simply updating the width set on the about.hbs view

**Comment by jpailthorpe** [comment]
I am going to review this page. We might change back the headers to not use the icon grid and instead use the original photos as in mockups. If so, this image will be removed anyway.

**Comment by msuen** [comment]
@jpailthorpe I would recommend using the original photos, as per mockups. Case Studies might need a better image, and the Chart the Course photo is particularly low-res, but across the board I think they look nicer and provide relevant context.

**Comment by jpailthorpe** [comment]
@msuen agreed for sure, hitting that tomorrow.

**Comment by jpailthorpe** [comment]
In the interest of time, lets just remove the background icon image from the header: 

`.c-article__header--bg-repeater {
  background-color: var(--secondary);
  ~background-image: url(../images/bg-repeater.png)~;`

<img width="1384" alt="screen shot 2017-01-24 at 5 27 31 pm" src="https://cloud.githubusercontent.com/assets/10051544/22269501/9c266d1a-e259-11e6-98c2-52b57c293e3a.png">

I think this looks cleaner, and then if we have more time, we can add the photos per mockups

**Comment by jpailthorpe** [comment]
I would do it myself but I don't know the gulp stuff and don't want to break the css file :)

**Comment by jpailthorpe** [comment]
done
