### ISSUE TITLE
Toolkit-Builder: Side menu shows no activities, but will print the ones previously chosen

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/city-accelerator-website#53]
I go through the builder, choosing activities and printing etc. 
I go back to the beginning of the builder, and click the Roadmap Activities side menu (there are no activities listed). 
I click "Print Roadmap" and it remembers all previous activities I had chosen, despite having the side menu be empty.

**Comment by jpailthorpe** [comment]
@esalling23 In one of the new fixes we will be removing the sidebar from the builder itself entirely, since we don't want users distracted from the main flow. So I THINK this is a nonissue?

**Comment by esalling23** [comment]
@jpailthorpe That would make this a nonissue, tho I did like being able to see what I had picked while still moving through the toolkit builder!

**Comment by jpailthorpe** [comment]
@esalling23 my rationale is distraction mostly and secondly users misunderstanding that feedback/trying to make mental connections between question and activity (we are trying to keep that a bit more "behind the scenes" so users dont explictly know it is question:activity 1:1) makes it a bit more magical
