### ISSUE TITLE
Global: when pasting a link from the site into facebook/slack/etc, the preview shows as Uncertainty dictionary. Instead, it should be a direct preview of the page being linked.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#54]
<img width="423" alt="screen shot 2017-01-10 at 12 27 20 pm" src="https://cloud.githubusercontent.com/assets/10051544/21816804/6d6e3ec4-d72f-11e6-8e09-4e6ee44456a4.png">

**Comment by esalling23** [comment]
The Uncertainty Dictionary is not listed in any of our files, other than in reference to a sublime project that no longer exists (in config.codekit3) -- This may be a cache issue?

**Comment by jpailthorpe** [comment]
Added metadata model to keystone. allows each page on the site (except for individual toolkit builder questions and activity modals) to have a completely sep. title and description when sharing on social media. This is the autogenerated thing that comes up when you post a link in facebook, slack, etc.

**Comment by jpailthorpe** [comment]
@esalling23 Can you also add an image field to this model?

**Comment by jpailthorpe** [comment]
meta data model ready for content. FIXED!
