### ISSUE TITLE
Toolkit-Builder: Next buttons cut off at large screens 

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/city-accelerator-website#57]
<img width="896" alt="screen shot 2017-01-11 at 11 15 35 am" src="https://cloud.githubusercontent.com/assets/11821504/21856373/ca44c4d6-d7ef-11e6-96cd-b3f2fd6cd00a.png">
Tested at 2560px - 1980px width

**Comment by esalling23** [comment]
No longer able to reproduce this, but looks like in general the design is not responsive at large screen sizes 
<img width="1140" alt="screen shot 2017-01-13 at 12 03 07 pm" src="https://cloud.githubusercontent.com/assets/11821504/21938211/6054612c-d988-11e6-82d1-e79b2ae5cb2b.png">

**Comment by jpailthorpe** [comment]
This seems to be fixed in the builder, but I did notice this happening on the mvp grid at the bottom section. Can you take another pass through and check/fix?

**Comment by jpailthorpe** [comment]
fixed
