### ISSUE TITLE
Frontpage - Text under header is too small on larger screens

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/city-accelerator-website#58]
<img width="1150" alt="screen shot 2017-01-11 at 11 26 48 am" src="https://cloud.githubusercontent.com/assets/11821504/21856734/073b4a44-d7f1-11e6-9fb9-7ac73418b04e.png">
Text could be a little larger starting at 1440px width screens

**Comment by jpailthorpe** [comment]
Not sure what happened, but now the text is not responsive across the site. Might just be lack of knowledge with how Mariano has setup his css classes. If so, feel free to ping him for information. 

This is the highest priority

**Comment by jpailthorpe** [comment]
fixed
