### ISSUE TITLE
Navigation 'menu' button outline

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/city-accelerator-website#59]
<img width="157" alt="screen shot 2017-01-11 at 11 45 24 am" src="https://cloud.githubusercontent.com/assets/11821504/21857470/8b5ea436-d7f3-11e6-8856-c70364fa7d46.png"><img width="157" alt="screen shot 2017-01-11 at 11 49 23 am" src="https://cloud.githubusercontent.com/assets/11821504/21857609/049c54ce-d7f4-11e6-950a-d51bb4dc2916.png">
Small css issue - clicking on menu button leaves behind outline

**Comment by jpailthorpe** [comment]
fixed
