### ISSUE TITLE
Guide_Page_Navigation(alldevices): Need each page of the guide to have a "forward/back" link to go on to the next page at top and bottom of content

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#6]
each guide page needs a next and back link to advance from one page to the next without having to use the sidebar nav. These should be near the top AS WELL AS the bottom and always just link to the next page in the order the guide is constructed. This is displayed in the mockup below. 

I think its fine if we just hardcode the progression so that the forward link would just pull the next guide page in order (rather than having to create a "link" field in the model). If its easier to just have hardcoded next and back in the template instead of the title of each page I am fine with that. 

https://marvelapp.com/2gjiih4/screen/17893895

**Comment by MarianoMiguel** [comment]
@jpailthorpe @johnnycrich Having trouble running /guide locally but this should work/look as per the mockups. What I'm going to need from you guys, is that you take a look at the `partials/articleNav.hbs` file and replace the placeholder content (# link, "Page Title" anchor) with the the actual previous/next links and title variables from Keystone.

**Comment by jpailthorpe** [comment]
@MarianoMiguel great np. I reassigned to me for this issue then, and if running into problems will make a new issue and ref. this one.

**Comment by jpailthorpe** [comment]
Reassign to @johnnycrich since it is a bit more complicated than i thought

**Comment by esalling23** [comment]
@MarianoMiguel @jpailthorpe @johnnycrich the /guide page requires a GuideHome model to be made in Keystone, which is why its working fine on QA! Just for future reference!

**Comment by esalling23** [comment]
I just pushed the fix for this!

**Comment by jpailthorpe** [comment]
confirmed fix
