### ISSUE TITLE
Mobile screen brand logo top padding

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/city-accelerator-website#60]
<img width="333" alt="screen shot 2017-01-11 at 11 52 18 am" src="https://cloud.githubusercontent.com/assets/11821504/21857761/9beab06e-d7f4-11e6-8bdc-96e6dd55cf9a.png">
Could use a bit more padding above the "Public Engagement Roadmap" logo

**Comment by jpailthorpe** [comment]
seems fixed to me!
