### ISSUE TITLE
Universal: Hover and click indicators

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/city-accelerator-website#62]
This is just an enhancement idea, to add hover or click indicators wherever they make sense throughout the site (buttons, menu links, etc)

**Comment by jpailthorpe** [comment]
def. I think links should be colored + dif. style to offset across site. 
![eme-about-1219-ms](https://cloud.githubusercontent.com/assets/10051544/22043408/77cc6f86-dcdd-11e6-911d-e0e7986d069a.png)

**Comment by jpailthorpe** [comment]
note for this, lets focus on the links and the titles in program goals. making sure it matches font + size + style.

**Comment by jpailthorpe** [comment]
This looks good @esalling23. Lets now get the other links looking like this in other areas of the site if it isn't too much work.

**Comment by jpailthorpe** [comment]
all set
