### ISSUE TITLE
Create breakpoints and implement responsiveness at screen sizes 2456px+

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/city-accelerator-website#63]
Currently the last breakpoint is at 2000px, and many screens do not handle anything larger than 1440px very well, as can be seen in the Toolkit Builder below
<img width="1140" alt="screen shot 2017-01-13 at 12 03 07 pm" src="https://cloud.githubusercontent.com/assets/11821504/21939536/37637e50-d98e-11e6-95c5-0840ff36e427.png">

**Comment by jpailthorpe** [comment]
I will review

**Comment by msuen** [comment]
I would recommend not creating additional breakpoints —  the investment for design and development for such an edge case probably isn't worthwhile. Instead, we could (1) fix the diamond positioning in the progress bar, and (2) simply implement a max width on the card that is not a percentage.

**Comment by jpailthorpe** [comment]
@msuen good point, and I think the site is better now that the css file was recompiled. I'm not sure how long we were seeing a dif. version. 

I def. think implementing a max width on the card is important here though.

**Comment by jpailthorpe** [comment]
this is rep. of #88 , closing here, follow progress there.
