### ISSUE TITLE
Print button on MVP screen has a lot of padding on small screens, but fits into the corner on large screens

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/city-accelerator-website#64]
@jpailthorpe Just making sure this was done on purpose and matches design, since it looks like a bug. 

On small screens:
<img width="782" alt="screen shot 2017-01-13 at 2 12 46 pm" src="https://cloud.githubusercontent.com/assets/11821504/21942353/bd896d58-d99a-11e6-94ea-369de8ddf434.png">

On large screens: 
<img width="314" alt="screen shot 2017-01-13 at 2 16 29 pm" src="https://cloud.githubusercontent.com/assets/11821504/21942387/e9edb11a-d99a-11e6-8d3f-3040da63ef34.png">

**Comment by jpailthorpe** [comment]
The print button should be removed on screens lower than the 800px breakpoint. Since the sidebar button floats to the bottom and printing can be accessed through there, it is much cleaner. 

The way it works on other screens is fine, even with dif. sizing.

**Comment by esalling23** [comment]
@jpailthorpe I can remove it when the sidebar appears at the bottom, but it still floats on larger screens, which I think looks weird when it could be settled into the corner perfectly

**Comment by jpailthorpe** [comment]
@esalling23 you are right. I think the reason this was designed this way originally was due to not knowing how much content would be on screen, and not having a sidebar at all. Since this has changed, I agree with your suggestion. Lets do that

**Comment by jpailthorpe** [comment]
fixed
