### ISSUE TITLE
ToolkitBuilder Questions Content: all text in toolkit process builder (now known as the pre-screen questionnaire) is hardcoded. Lets make the following copy changes

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#66]
“Have you created a logic model, or any other project planning document with identified project milestones?” should be changed to, “Have you created a logic model, or any other project planning and evaluation tool?”

“Do you know how you’re going to update your community during the project?” should be changed to “Do you know how you’re going to provide updates to the public during and after the project?”

“Do you know all the tools you’re going to use and how to use them effectively?” should be changed to; “Do you feel like you have a good understanding of all the tools you’re going to use (digital and analog) and how to use them effectively?

I will match which questions these are in a bit so its easier to find + fix

**Comment by esalling23** [comment]
@jpailthorpe These are the "Question" field on the activities, these are not hard coded!

https://qa.cityaccelerator.net/keystone/activities/585965d5ab140bbb1be16d01 this is the first one!

**Comment by jpailthorpe** [comment]
doh. im a dummy. fixed in keystone
