### ISSUE TITLE
Homepage: Incorporate PER logo into design.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#70]
Will do first draft then consult with Aidan. 

https://drive.google.com/open?id=0B2iJJeD7RJtgWFJLUGx1YlA4Z28

**Comment by msuen** [comment]
I took a stab — how does this look?
<img width="1424" alt="screen shot 2017-01-20 at 3 51 17 pm" src="https://cloud.githubusercontent.com/assets/2809369/22165168/6a52db72-df28-11e6-8efb-f81cf8ab4880.png">

**Comment by msuen** [comment]
I took a stab. How does this look?

<img width="1425" alt="screen shot 2017-01-20 at 3 52 41 pm" src="https://cloud.githubusercontent.com/assets/2809369/22165179/8303d892-df28-11e6-8779-661dc683feac.png">

**Comment by jpailthorpe** [comment]
HAHA, just saw your post @msuen.  I  came here to post my version of this, which is exactly the same as yours. So, yes. Assigning Erica. here. 

<img width="974" alt="screen shot 2017-01-24 at 5 07 25 pm" src="https://cloud.githubusercontent.com/assets/10051544/22268798/d04e0b78-e256-11e6-9940-8ac3c1aebd52.png">

**Comment by jpailthorpe** [comment]
Make sure @MarianoMiguel and @esalling23 you match up on this, since mariano is working on the size via #79

**Comment by jpailthorpe** [comment]
finished!
