### ISSUE TITLE
Homepage-footer: Redesign of footer 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#71]
- [x] Remove sentence
- [x] Make logos white with color fill, not saturated 
- [x] incorporate CC logo 
- [x] copy edit contact us sentence

**Comment by jpailthorpe** [comment]
Jordan hits first draft then aidan approval

**Comment by msuen** [comment]
See my take on logos here: #90

**Comment by jpailthorpe** [comment]
noted!

**Comment by jpailthorpe** [comment]
done
