### ISSUE TITLE
Guide: Section pages need some additional design attention

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#78]
Not sure what it is, maybe just removing the top or bottom navs to keep only one set, but need to address the weird look of this page. 

![qa cityaccelerator net-guide-calibrating-the-instruments 1](https://cloud.githubusercontent.com/assets/10051544/22048094/da697948-dcf8-11e6-9a64-7dafc7ce948e.png)

**Comment by msuen** [comment]
@jpailthorpe How feasible is this in a one-day period alongside your other fixes, @MarianoMiguel? It's one set of nav links, but fixed on the page during your scroll down the content. So, once you scroll down and "Executive Summary / BACK" and "Defining Citizenship / NEXT" hits the top of the screen, it stays there all the way until you hit the bottom.

**Comment by jpailthorpe** [comment]
@MarianoMiguel this is exactly what I think would be best, but of course then becoming fixed on mobile, right? We can also have Erica do this here.

**Comment by jpailthorpe** [comment]
Erica is taking this on. We are basically going to have the links float, but only above the 1200 breakpoint. otherwise we run into the annoying thing where the links overlaps the text. under 1200 they nav links will just stay at the bottom of the article. We determined this to be the best solution because it 1. allows for the nav links to help flesh out the aesthetic look of the page on bigger screens and 2. avoids any user exp. problems that arise from overlapping titles/text (1200 specifically because it is already a breakpoint and it is the smallest breakpoint before text overlaps. 800 still runs into that problem). 

That all being said, If unknown things pop up from this solution, we are going to remove them from the top entirely and automatically fix them to the bottom.

**Comment by jpailthorpe** [comment]
done!
