### ISSUE TITLE
Guide_Sidebar: Not all guide pages and sections are being listed in the sidebar, but are viewable live

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#8]
"Going places” section as well as the two subsections underneath it are not listed in the sidebar, but are on the site (in keystone). (how is the sidebar pulling titles?) There are two additional pages under going places fyi.

**Comment by MarianoMiguel** [comment]
@jpailthorpe Apparently the method for pulling the links is a bit manual in that you have to define which sections to pull. e.g:

```
{{#each calibratingGuides}}
		{{#if this.isSection}}
		<h4 class="c-off-canvas__sub-title"><a class="c-off-canvas__link" href="/guide/{{this.guide_key}}">{{this.name}}</a></h4>
		{{/if}}
{{/each}}
{{#each calibratingGuides}}
		{{#ifeq this.isSection false}}
		<a class="c-off-canvas__link" href="/guide/{{this.guide_key}}">{{this.name}}</a>
		{{/ifeq}}
{{/each}}
```

So, I can try to put that section in assuming the keystone naming will be similar to what we already have i.e "goingPlaces". In terms of order, where should this section be placed?

**Comment by jpailthorpe** [comment]
@MarianoMiguel going places is the last section of the guide (same hierarchy level as Calibrating, etc.) and "additional engagement modalities" is a section page under going places 

GOING PLACES
     Additional Engagement Modalities.

**Comment by jpailthorpe** [comment]
Feel free to reassign to @johnnycrich Johnny if there is keystone confusion

**Comment by MarianoMiguel** [comment]
@johnnycrich Just added the going places section into the guide sidebar (each goingGuides...etc). I'm not sure if there's anything else necessary for it to work, so I'm reassigning to you just in case.

**Comment by jpailthorpe** [comment]
Looks like that last commit fixed everything. closing for now!
