### ISSUE TITLE
About page: updates for contact + team credits 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#83]
About page
Add credits for names
Add contact info

**Comment by msuen** [comment]
@jpailthorpe Can you elaborate? What information do you need me to add exactly?

**Comment by jpailthorpe** [comment]
@msuen oops sorry! this is notes for me. I will do a draft and then show you for approval/ask for advice, but I will handle it (comes from stakeholders). 

My question to you and @MarianoMiguel is do you want to be named in credits? and if so, Weirdo or individual names?

**Comment by jpailthorpe** [comment]
@codeworthy both credits and contact information is in Keystone ready for edits + entry. reassigning here.

**Comment by jpailthorpe** [comment]
added to production
