### ISSUE TITLE
Toolkit-grid: When you have no activities in your roadmap, text should appear that tells the user what to do. This is already in code, but not appearing properly on site. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#85]
See screenshot. Here I unchecked display none to show it appearing. Obviously this is not the solution since it remains even when there are activities in the sidebar, but wanted to show what i mean. 

The reason I want this working is it offers us a way to help with UX without additional feature design. 

![screen shot 2017-01-19 at 3 11 31 pm](https://cloud.githubusercontent.com/assets/10051544/22123308/2d20e980-de59-11e6-943e-d2fafeeb562d.png)

  <aside class="s-tool__sidebar c-off-canvas js-off-canvas {{#ifeq hidden true}}hidden-el{{/ifeq}}" aria-hidden="true">

    <button class="c-off-canvas__toggle js-off-canvas-toggle" data-expanded="Hide Window" data-collapsed="Your Roadmap" aria-pressed="false">Your Roadmap</button>

    <div class="c-off-canvas__content">
      <h3 class="c-off-canvas__title">Your Roadmap</h3>
      <p class="c-off-canvas__text js-tool-sidebar-empty" aria-hidden="false">No activities in your roadmap yet!</p>
      <div class="js-tool-sidebar-content"></div>
    </div>
    <div class="c-off-canvas__actions">
      <button class="c-btn c-btn--blue c-btn--full js-tool-print-mvp">Print Roadmap</button>
    </div>
  </aside>

**Comment by msuen** [comment]
@jpailthorpe Can you elaborate?

**Comment by jpailthorpe** [comment]
fixed!
