### ISSUE TITLE
Toolkit: If a user has an activity modal open and then clicks an external link, upon hitting the back browser button they are taken to the start of the builder, not activity grid.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#86]
**This is only a problem if a user's setting is to open external links within the same tab/window.** 

This is quite annoying and I assume will be a typical use case. I am okay that it doesn't go back to the open modal, though this would be ideal. 

The bigger problem is that is goes to the builder process tool, which is really confusing to someone who might not have even entered that screen to begin with. 

Another solution would just to have all external links open in a new tab or window, if possible. 

reproduce:
1. navigate to toolkit activity grid
2. open any activity.
3. click on any external link (basically any link inside the content of the activity) 
4. once there, click back button. 
5. taken to builder tool first screen.

**Comment by MarianoMiguel** [comment]
@jpailthorpe This doesn't seem to be the case for me :( Upon opening any activity, the URL in your toolbar should update to something like https://qa.cityaccelerator.net/toolkit-builder#step=1.1

From there, if you click any external link and then go back, the URL should be back to https://qa.cityaccelerator.net/toolkit-builder#step=1.1

Is your toolbar URL being updated? Or does it stay at https://qa.cityaccelerator.net/toolkit-builder?

**Comment by esalling23** [comment]
@MarianoMiguel It does return the player to the screen with the modal open, however it sends the player to the toolkit builder upon closing that modal, rather than to the MVP grid

**Comment by MarianoMiguel** [comment]
@esalling23 Oh! Yeah that makes sense. Thanks :)

**Comment by jpailthorpe** [comment]
This is still happening (though admittedly, its a super not priority thing

**Comment by jpailthorpe** [comment]
same! fixed!
