### ISSUE TITLE
Toolkit process builder: score screen gets cutoff on mobile devices lower than 425pxwidth

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#89]
![qa cityaccelerator net-toolkit-builder 2](https://cloud.githubusercontent.com/assets/10051544/22126056/1fdf74f2-de64-11e6-8c7b-56b6b083da41.png)

between 320-425 is where is cuts

**Comment by jpailthorpe** [comment]
![screen shot 2017-01-23 at 4 40 26 pm](https://cloud.githubusercontent.com/assets/10051544/22223753/0d28bd22-e18a-11e6-8d33-5128cffed665.png)

![screen shot 2017-01-23 at 4 40 19 pm](https://cloud.githubusercontent.com/assets/10051544/22223772/1296e7b6-e18a-11e6-8cd0-93596e6e3669.png)

still seeing this error on screen sizes smaller than 425. Iphone6 plus is fine, but anything lower cuts off.

**Comment by jpailthorpe** [comment]
also checked code to make sure your commits are in the build and they are, so it must just be another issue.

**Comment by MarianoMiguel** [comment]
@jpailthorpe I think the issue here is that style.css got probably overwritten by another commit. Let me re-compile it and push again and it should be fine.

**Comment by jpailthorpe** [comment]
you are 100% correct. verified as fixed! thanks!
