### ISSUE TITLE
home page: link to all activites on toolkit card incorrectly is linked to the homepage. should be mvp grid

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#99]
make sure when clicking on "view all activities" it takes you to here 
https://qa.cityaccelerator.net/toolkit-builder#step=grid

**Comment by esalling23** [comment]
cannot reproduce

**Comment by jpailthorpe** [comment]
was removed in latest revision round, so no longer a thing
